### PR TITLE
Feature/database

### PR DESCRIPTION
**Pull request by NickTAdams**
@melvinest :

Here is my pull request for the database, this is in response to tickets:
<blockquote class="trello-card"><a href="https://trello.com/c/RACuawTC/34-fix-bug-by-makearray-function-causes-each-element-of-array-to-have-length-200-instead-of-a-single-element">Fix bug by makeArray function - causes each element of array to have length 200 instead of a single element</a></blockquote>
<blockquote class="trello-card"><a href="https://trello.com/c/nusLX9OH/2-3-spin-up-database-in-mongodb">3 - Spin up database in mongoDB</a></blockquote>

The objective was to spin up a database using the seed data, with 200 documents corresponding to the seed data.

The relevant changes are in the **databases** folder.

- **db-helpers.js** contains the helper functions for generating the schema and model.
- **seed-database.js** contains the commands for seeding the database, also run from the script `npm start`.
- **seed-database.test.js** tests the database for data and that there are 200 records in it. Note that you must run `npm start` before running these tests. This is to save time from adding the records each time you run tests.

I also fixed a bug in the **data.js** helper functions for arrays, fixing the number of items that appeared in each list.

Looking forward to your feedback,
Nick

### CODE REVIEW

**Comment by melvinest** [comment]
Hey Nick,
I'll start reviewing this tomorrow morning. I'll get back to you once I'm done.

**Comment by melvinest** [comment]
@NickTAdams 
hey Nick, 

The code is generally good. I did not see any major issue. 

I only have minor comments/suggestions but this is entirely optional and will not affect your code. Here they are:

- I see that you are using promises to promisify the .save() function of mongoose (see seed-database.js, line 44). Mongoose actually has promise functionality for .save() and .exec(). To access that, return .save() from your function without putting any callbacks inside it. You also have to define mongoose.promise as the es6 promise. If you want more info regarding this, check my code (line 3, 39 and 41). [https://github.com/teamwelp/reviews/blob/feat/mockdata/db/models/review.js](url).

- Regarding your test for your database, it might be better to add another test that will compare a single data from your generateFakeData function and a single document of the same businessId to see if all fields were successfully added. You just have to add an expect() to your first test comparing the fake data and the DB data.

After you review my comments/suggestions you can merge this branch to your master.

**Comment by NickTAdams** [comment]
@melvinest 
Thanks for the feedback! Thanks for the guidance on mongoose and promises, I remember struggling a little with it before settling on promisifying it. I'll incorporate those changes in a bit.
-Nick

**Comment by NickTAdams** [comment]
@melvinest 
I have implemented your feedback and am merging now.
Thanks!
Nick

**Pull request merged**
