### PR TITLE
Feature/data generation

### PR DESCRIPTION
**Pull request by NickTAdams**
Hi @awhitneye ,
This PR relates to tickets:

<blockquote class="trello-card"><a href="https://trello.com/c/zW9x6nvn/1-generate-seed-data-based-on-schema">Generate seed data based on schema</a></blockquote>
<blockquote class="trello-card"><a href="https://trello.com/c/MvUt3R6M/13-write-tests-for-seed-data">Write tests for seed data</a></blockquote>
<blockquote class="trello-card"><a href="https://trello.com/c/1eYFbUj7/29-implement-my-first-coverage-test-on-seed-data-generation">Implement my first coverage test on seed data generation</a></blockquote>

The objective was to make an object with properties matching that of the [data schema](https://docs.google.com/document/d/1k6_clzZPI17XqMRUo633GfOu080YJ_OARLzg9nruEog/edit?usp=sharing), with each property referring to an array of length 200. These arrays contain values that match the types in the schema, and can be fixed or random. 

The relevant changes are mostly in the data folder:
- **names.js** contains the data generation script that we worked on together.
- **data.js** contains the function _generateFakeData_ and it's helper functions. They should generate the data object.
- **data.test.js** contains the test code. It should test the shape, types, and randomness of the generated data object.

Please review and tell me what you think!
Thanks,
Nick

### CODE REVIEW

**Comment by awhitneye** [comment]
Looks good.  My immediate concern is that I'm seeing that this branch has conflicts that must be resolved in package.json, as identified by Git.  Let me know if you can resolve this ahead of the request, or if this is a false flag.  I can't see where this conflict might lie.

**Comment by NickTAdams** [comment]
@awhitneye 
Looks like the problem was in here:

```
<<<<<<< feature/data-generation
  "scripts": {
    "test": "jest --coverage"
  },
=======
  "scripts": {},
>>>>>>> master
```

where I added on to the scripts property. I kept the lines from **feature/data-generation** when I resolved. Clear to merge pull request?

Nick

**Comment by awhitneye** [comment]
I would consider at some point in the future reviewing variable names for the function randomArrayData in data.js (doesn't necessarily describe the action of the function, I only understood that later on in watching it work) and the const objectField in data.test.js.  
I would also consider factoring out some repeated logic in the names.js file.
This is just stylistic - If pressed for time, I'm comfortable with merging and maybe mark this stylistic refactoring for later.  Otherwise, might as well complete this now.

**Comment by NickTAdams** [comment]
@awhitneye  -
I went and did the following:

- in **data.js** I changed the name of _randomArrayData_ to _generateRandomArrayOfItems_. Does that help? I'm unsure on a better name. What it does is generates a random array of items based on randomly chosen items from another array, using _randomItemFromArray_ as a helper function.
- in **names.js** I deleted the _users_ function, since it is never used in this implementation.

Cheers,
Nick

**Comment by awhitneye** [comment]
Sounds good!

**Comment by NickTAdams** [comment]
Merged!

**Pull request merged**
